name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Test build
        run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-praktikan63

            PROJECT_DIR="${HOME}/senpro/538251/modul02/senpro-github-action"

            echo "Cek folder project"

            if [ ! -d "${PROJECT_DIR}/.git" ]; then
              echo "Repository belum di-clone. Cloning..."

              mkdir -p "${HOME}/senpro/538251/modul02"
              cd "${HOME}/senpro/538251/modul02"

              git clone https://github.com/ggalangswt/senpro-github-action.git
            else
              echo "Repository sudah ada. Mengambil perubahan terbaru..."

              cd "${PROJECT_DIR}"
              git restore .
              git pull origin main
            fi

            cd "${PROJECT_DIR}"

            echo "Install Package dan Build Project"
            npm install
            npm run build